require(tidyverse)

licence.open <- c("CC BY","CC BY-SA","http://creativecommons.org/licenses/by/4.0/","http://creativecommons.org/licenses/by/4.0","https://creativecommons.org/licenses/by/4.0/","https://creativecommons.org/licenses/by-sa/4.0/","https://creativecommons.org/licenses/by-sa/4.0/"," http://creativecommons.org/licenses/by/3.0/")
licence.free <- c("CC BY-NC","CC BY-NC-SA","CC BY-ND","CC BY NC-ND","http://creativecommons.org/licenses/by-nc-sa/4.0/","http://creativecommons.org/licenses/by-nc-nd/4.0/","http://creativecommons.org/licenses/by-nc-nd/3.0/")   

# Require a table generated by with the following informations

data <- read_csv("Data/OA-Information.csv")

coat.result <- data %>% 
  mutate (coat.place = case_when(
    oa.place == "publisher" ~ 1, 
    oa.place == "repository" ~ 2,
    T ~ 4)) %>%
  mutate(coat.version = case_when(
    version == "info:eu-repo/semantics/publishedVersion" ~ 1,
    version == "info:eu-repo/semantics/acceptedVersion" ~ 2,
    version == "info:eu-repo/semantics/submittedVersion" ~ 3,
    T  ~ 4
  )) %>%
  mutate(coat.licence = case_when(
    licence.url %in% licence.open ~ 1,
    licence.url %in% licence.free ~ 2,
    !is.na(licence.url) ~ 3,
    T ~ 4
  )) %>%
  mutate(coat.embargo = case_when(
    embargo.time == 0 ~ 1,
    embargo.time < 6 ~ 2,
    embargo.time < 12 ~ 3,
    T ~ 4
  )) %>%
  mutate(coat.condition = case_when(
    APC == 0 ~ 1,
    APC > 0 & is.hybrid == F ~ 2,
    APC > 0 & is.hybrid == T ~ 3,
    oa.place == 2 ~ 1,
    coat.version != 4 ~ 1,
    T ~ 4
  )) %>% 
  select(identifier, year,insitution,country, coat.version,coat.licence,coat.place,coat.embargo,coat.condition)


write_csv(coat.result,"Data/COAT.csv")
